# Generated by Django 6.0.2 on 2026-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='teacher_cvs/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject'),
        ),
    ]
