# Generated by Django 6.0.2 on 2026-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher_classes_teacher_cv_teacher_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=10),
        ),
    ]
