# Generated by Django 6.0.2 on 2026-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=10),
        ),
    ]
